---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 382451716-lOkJSbOsITGvU6vSSu8q8xWJmpf6skaozfTtkLIf
:access_token_secret: scAoB4unUwwZAi22IjdcyeqIY07HLaXTLT4r9XSunDJtm
